[[files]]
name = ".gitignore"
action = "copy"
source = "./src/.gitignore"
target = "{{ .User.home }}"
mode = 420

[[files]]
name = "testFile.txt"
action = "copy"
source = "./src/.config"
target = "{{ .User.home }}/.config"
mode = 420
