[provider]
name = "cargo"
elevated = false # Cargo operates at user level

[provider.detection]
binary = "cargo"
files = ["~/.cargo/bin/cargo", "~/.rustup"]
distributions = ["linux", "darwin", "windows"] # Cross-platform

[provider.commands]
install = "install"
update = "install-update --all" # Use cargo-update to update all packages
remove = "uninstall"
list = "install --list"
search = "search"
clean = "cache --autoclean"

[provider.corePackages]
openssl = []          # Cargo doesn't need to install OpenSSL
build-essentials = [] # Cargo doesn't need build essentials

[provider.repository.paths]
registry = "~/.cargo/registry"
cache = "~/.cargo/cache"
config = "~/.cargo/config.toml"

[[provider.install.steps]]
action = "command"
exec = "curl"
args = [
  "--proto",
  "=https",
  "--tlsv1.2",
  "-sSf",
  "https://sh.rustup.rs",
  "-o",
  "/tmp/rustup-init.sh",
]

[[provider.install.steps]]
action = "command"
exec = "sh"
args = ["/tmp/rustup-init.sh", "-y"]

# Install cargo-update
[[provider.install.steps]]
action = "command"
exec = "cargo"
args = ["install", "cargo-update", "--features", "vendored-openssl"]

[[provider.remove.steps]]
action = "command"
exec = "rustup"
args = ["self", "uninstall", "-y"]

[[provider.repository.add.steps]]
action = "command"
exec = "cargo"
args = ["update"]  # Update registry index

[[provider.repository.add.steps]]
action = "write"
dest = "{{ .ConfigPath }}"
content = """
[registries.{{ .Name }}]
index = "{{ .URL }}"
"""
condition = "{{ .IsCustomRegistry }}" # Only for custom registries

[[provider.repository.add.steps]]
action = "command"
exec = "cargo"
args = ["login", "--registry", "{{ .Name }}", "{{ .Token }}"]
condition = "{{ .HasToken }}"                                 # Only if authentication token provided

[[provider.repository.remove.steps]]
action = "command"
exec = "cargo"
args = ["logout", "--registry", "{{ .Name }}"]
condition = "{{ .HasToken }}"

[[provider.repository.remove.steps]]
action = "remove_section"
path = "{{ .ConfigPath }}"
section = "registries.{{ .Name }}"
condition = "{{ .IsCustomRegistry }}"
