[provider]
name = "zypper"
elevated = true

[provider.detection]
binary = "zypper"
files = ["/etc/zypp", "/var/lib/zypp"]
distributions = ["opensuse", "suse"]   # Works on openSUSE and SUSE Linux

[provider.commands]
install = "install -y"
update = "update -y"
remove = "remove -y"
list = "packages --installed-only"
search = "search"
clean = "clean"

[provider.corePackages]
openssl = ["openssl", "libopenssl-devel"]
build-essentials = [
  "make",
  "cmake",
  "freetype-devel",
  "fontconfig-devel",
  "libxcb-devel",
  "libxkbcommon-devel",
]

[provider.repository.paths]
sources = "/etc/zypp/repos.d"
keys = "/etc/pki/rpm-gpg"

[[provider.repository.add.steps]]
action = "command"
exec = "zypper"
args = ["addrepo", "{{ .URL }}", "{{ .Name }}"]

[[provider.repository.add.steps]]
action = "download"
source = "{{ .KeyURL }}"
dest = "{{ .KeyPath }}"

[[provider.repository.add.steps]]
action = "command"
exec = "rpm"
args = ["--import", "{{ .KeyPath }}"]

[[provider.repository.add.steps]]
action = "command"
exec = "zypper"
args = ["refresh"]

[[provider.repository.remove.steps]]
action = "command"
exec = "zypper"
args = ["removerepo", "{{ .Name }}"]

[[provider.repository.remove.steps]]
action = "command"
exec = "rpm"
args = ["--erase", "gpg-pubkey-{{ .KeyID }}"]
