version: "2"

run:
  timeout: 5m
  tests: false

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell

  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true

    staticcheck:
      checks: ["all", "-ST1003"]

formatters:
  enable:
    - gofmt
    - goimports

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
