# .goreleaser.yaml

version: 2

env:
  - GO111MODULE=on

before:
  hooks:
    - go mod tidy

snapshot:
  version_template: "{{ incpatch .Version }}-next"

gomod:
  proxy: true

report_sizes: true

git:
  ignore_tags:
    - "{{ if not .IsNightly }}nightly{{ end }}"

metadata:
  mod_timestamp: "{{ .CommitTimestamp }}"

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - "7"
    ignore:
      - goos: windows
        goarch: arm
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{ .CommitDate }} -X main.builtBy=goreleaser -X main.treeState={{ .IsGitDirty }}

universal_binaries:
  - replace: false

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^test:"
      - "^test\\("
      - "merge conflict"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy
  groups:
    - title: Dependency updates
      regexp: '^.*?(.+)\(deps\)!?:.+$'
      order: 300
    - title: "New Features"
      regexp: '^.*?feat(\(.+\))??!?:.+$'
      order: 100
    - title: "Security updates"
      regexp: '^.*?sec(\(.+\))??!?:.+$'
      order: 150
    - title: "Bug fixes"
      regexp: '^.*?(fix|refactor)(\(.+\))??!?:.+$'
      order: 200
    - title: "Documentation updates"
      regexp: ^.*?docs?(\(.+\))??!?:.+$
      order: 400
    - title: "Build process updates"
      regexp: ^.*?(build|ci)(\(.+\))??!?:.+$
      order: 400
    - title: Other work
      order: 9999

archives:
  - name_template: >-
      {{- .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end -}}
    # Using the new format for archives configuration
    formats: ["tar.gz"]
    format_overrides:
      - goos: windows
        formats: ["zip"]
    builds_info:
      group: root
      owner: root

nfpms:
  - file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    id: packages
    homepage: https://github.com/fynxlabs/rwr
    description: "Rinse, Wash, Repeat (RWR) - Configuration Management Tool"
    maintainer: "Levi Smith <levi@fynxlabs.io>"
    license: MIT
    vendor: FynxLabs
    bindir: /usr/bin
    section: utils
    formats:
      - apk
      - deb
      - rpm
      - archlinux
    recommends:
      - git
      - curl
      - wget

homebrew:
  - repository:
      owner: FynxLabs
      name: brew-tap
      git:
        url: "ssh://git@github.com/FynxLabs/brew-tap.git"
        private_key: "{{ .Env.HOMEBREW_TAP_DEPLOY_KEY }}"
    directory: Formula
    goarm: "7"
    homepage: "https://github.com/fynxlabs/rwr"
    description: "Rinse, Wash, Repeat (RWR) - Configuration Management Tool"
    license: MIT

release:
  name_template: "v{{ .Version }}"
  footer: |
    **Full Changelog**: https://github.com/fynxlabs/rwr/compare/{{ .PreviousTag }}...{{ if .IsNightly }}nightly{{ else }}{{ .Tag }}{{ end }}
