[tools]
go = "1.23"
dagger = "latest"
goreleaser = "latest"

[tasks]
# Local development commands (no Dagger)
build = "go build ."  # Simple local build
test = "go test -v ./..."  # Simple local tests

# Dagger-based commands
dagger-local = "dagger call ci --ref=local --github-token='' --homebrew-token=''"  # Just run tests through Dagger pipeline
dagger-ci = "dagger call ci --ref=$GITHUB_REF_NAME"  # Full CI pipeline with publishing
