[tools]
go = "1.23"
dagger = "latest"
goreleaser = "latest"

[tasks]
# Local development commands (no Dagger)
build = "go build ."  # Simple local build
test = "go test -v ./..."  # Simple local tests

# Dagger-based commands
dagger-test = "dagger call ci"  # Just run tests through Dagger pipeline
dagger-local = "dagger call ci --skip-publish=true"  # Test full pipeline without publishing
dagger-ci = "dagger call ci --ref=$GITHUB_REF_NAME"  # Full CI pipeline with publishing
