[tools]
go = "1.25"
goreleaser = "latest"
gotestsum = "latest"

[env]
DAGGER_NO_NAG=1

[tasks]
# Local development commands (no Dagger)
build = "go build ."  # Simple local build
test = "gotestsum --format pkgname --jsonfile /tmp/gotest.json -- ./..."  # Formatted tests with gotestsum
"test:raw" = "go test -v ./..."  # Raw test output without formatting

# Unit test commands (formatted with gotestsum)
"test:unit" = "gotestsum --format pkgname --jsonfile /tmp/gotest.json -- ./internal/..."  # All internal package tests
"test:helpers" = "gotestsum --format testname -- ./internal/helpers"  # Helpers package tests
"test:processors" = "gotestsum --format testname -- ./internal/processors"  # Processors package tests
"test:system" = "gotestsum --format testname -- ./internal/system"  # System package tests
"test:coverage" = "gotestsum --format pkgname -- -cover ./internal/..."  # Test with coverage report

# Watch mode for development
"test:watch" = "gotestsum --watch --format testname"  # Watch for file changes and run tests

# Raw test commands (without formatting)
"test:unit:raw" = "go test ./internal/... -v"  # Raw internal package tests
"test:helpers:raw" = "go test ./internal/helpers -v"  # Raw helpers tests
"test:processors:raw" = "go test ./internal/processors -v"  # Raw processors tests
"test:system:raw" = "go test ./internal/system -v"  # Raw system tests
