# Essential services for all Ubuntu systems
services:
  - names:
      - ufw
      - ssh
      - cron
    action: enable

  # Development services for dev profile
  - names:
      - docker
      - nginx
    profiles: [dev]
    action: enable

  # Server services for server profile
  - names:
      - apache2
      - mysql
      - fail2ban
    profiles: [server]
    action: enable

  # Desktop services for desktop profile
  - names:
      - bluetooth
      - cups
    profiles: [desktop]
    action: enable

  # Disable unnecessary services on minimal systems
  - names:
      - snapd
      - ModemManager
    profiles: [minimal]
    action: disable
