packageManagers = [
    { name = "cargo", action = "install" },
    { name = "brew", action = "install" },
]

[blueprints]
format = "toml"
location = "."
order = [
    "repositories",
    "packages",
    "files",
    "fonts",
    "services",
    "git",
    "scripts",
    "users",
    "ssh_keys",
    "configuration",
]
