[[packages]]
names = ["docker-desktop", "vscode", "vim", "tree"]
action = "install"
package_manager = "chocolatey"

[[packages]]
names = ["Microsoft.WindowsTerminal"]
action = "install"
package_manager = "winget"