[[scripts]]
name = "setup-dev-env"
action = "inline"
content = """#!/bin/bash
echo "Setting up development environment for {{ .User.username }}"

# Create common directories
mkdir -p {{ .User.home }}/projects
mkdir -p {{ .User.home }}/.local/bin

# Set permissions
chmod 755 {{ .User.home }}/.local/bin

echo "Development environment ready!\""""
asUser = "{{ .User.username }}"

[[scripts]]
name = "install-node"
action = "inline"
content = """#!/bin/bash
# Install Node.js using package manager
if command -v apt &> /dev/null; then
    curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
    sudo apt-get install -y nodejs
elif command -v brew &> /dev/null; then
    brew install node
else
    echo "No supported package manager found"
    exit 1
fi

echo "Node.js installed successfully"
node --version
npm --version"""
asUser = "root"

[[scripts]]
name = "update-system"
action = "inline"
content = """#!/bin/bash
echo "Updating system packages..."

if command -v apt &> /dev/null; then
    sudo apt update && sudo apt upgrade -y
elif command -v dnf &> /dev/null; then
    sudo dnf update -y
elif command -v pacman &> /dev/null; then
    sudo pacman -Syu --noconfirm
elif command -v brew &> /dev/null; then
    brew update && brew upgrade
else
    echo "No supported package manager found"
    exit 1
fi

echo "System update complete!\""""
asUser = "{{ .User.username }}"