[blueprints]
format = "toml"
location = "."
order = [
    "bootstrap",
    "packages",
    "files",
    "services",
    "git",
    "scripts",
    "ssh_keys"
]

[[packageManagers]]
name = "cargo"
action = "install"

[[packageManagers]]
name = "brew"
action = "install"