[[files]]
name = ".bashrc"
action = "create"
target = "{{ .User.home }}/"
content = """
# Custom .bashrc content
alias ll='ls -alF'
export PATH=$PATH:$HOME/.local/bin
"""

[[files]]
name = ".gitignore"
action = "copy"
target = "{{ .User.home }}/"
source = "./src/"

[[directories]]
name = ".config"
action = "copy"
source = "./src/"
target = "{{ .User.home }}/"

[[templates]]
name = ".profile"
action = "copy"
source = "./src/"
target = "{{ .User.home }}/"