# Essential system scripts for all macOS systems
[[scripts]]
name = "update-system"
content = """#!/bin/bash
brew update && brew upgrade
brew cleanup
"""
mode = "755"

[[scripts]]
name = "setup-homebrew-permissions"
content = """#!/bin/bash
sudo chown -R $(whoami) /usr/local/var/homebrew
sudo chmod u+w /usr/local/var/homebrew
"""
mode = "755"

# Development setup for dev profile
[[scripts]]
name = "setup-developer-tools"
content = """#!/bin/bash
xcode-select --install
sudo xcodebuild -license accept
"""
profiles = ["dev"]
mode = "755"

[[scripts]]
name = "configure-git"
content = """#!/bin/bash
git config --global init.defaultBranch main
git config --global pull.rebase false
"""
profiles = ["dev"]
mode = "755"

# Desktop customization for desktop profile
[[scripts]]
name = "configure-dock"
content = """#!/bin/bash
defaults write com.apple.dock autohide -bool true
defaults write com.apple.dock tilesize -int 48
killall Dock
"""
profiles = ["desktop"]
mode = "755"