# Base system script
[[scripts]]
name = "update_system"
action = "run"
elevated = true
content = """
#!/bin/bash
dnf update -y
echo "System updated successfully"
"""

# Development setup
[[scripts]]
name = "setup_dev_environment"
profiles = ["dev"]
action = "run"
content = """
#!/bin/bash
mkdir -p "{{ .User.Home }}/Projects"
echo 'alias ll="ls -alF"' >> "{{ .User.Home }}/.bashrc"
echo "Development environment setup complete"
"""

# Docker setup
[[scripts]]
name = "docker_user_setup"
profiles = ["docker"]
action = "run"
elevated = true
content = """
#!/bin/bash
usermod -a -G docker "{{ .User.Username }}"
systemctl enable docker
systemctl start docker
echo "Docker setup complete"
"""