# Default personal SSH key - always created
[[ssh_keys]]
name = "id_ed25519"
type = "ed25519"
path = "{{ .User.Home }}/.ssh/"
comment = "{{ .User.Username }}@personal"
no_passphrase = false
copy_to_github = false

# Work-specific SSH key
[[ssh_keys]]
name = "id_work"
profiles = ["work"]
type = "ed25519"
path = "{{ .User.Home }}/.ssh/"
comment = "{{ .User.Username }}@company.com"
no_passphrase = false
copy_to_github = false

# GitHub-specific SSH key with automatic upload
[[ssh_keys]]
name = "id_github"
profiles = ["dev", "github"]
type = "ed25519"
path = "{{ .User.Home }}/.ssh/"
comment = "{{ .User.Username }}@github"
no_passphrase = true
copy_to_github = true
github_title = "{{ .User.Username }} Development Machine"

# Legacy RSA key for older systems
[[ssh_keys]]
name = "id_rsa_legacy"
profiles = ["legacy", "work"]
type = "rsa"
path = "{{ .User.Home }}/.ssh/"
comment = "{{ .User.Username }}@legacy-systems"
no_passphrase = false
copy_to_github = false

# Server deployment key
[[ssh_keys]]
name = "id_deploy"
profiles = ["deploy", "work"]
type = "ed25519"
path = "{{ .User.Home }}/.ssh/"
comment = "{{ .User.Username }}@deployment"
no_passphrase = true
copy_to_github = false

# Gaming/Steam remote play key
[[ssh_keys]]
name = "id_gaming"
profiles = ["gaming"]
type = "ed25519"
path = "{{ .User.Home }}/.ssh/"
comment = "{{ .User.Username }}@gaming-rig"
no_passphrase = true
copy_to_github = false

# Backup server key
[[ssh_keys]]
name = "id_backup"
profiles = ["backup", "personal"]
type = "ed25519"
path = "{{ .User.Home }}/.ssh/"
comment = "{{ .User.Username }}@backup-server"
no_passphrase = false
copy_to_github = false

# Main RWR SSH key for configuration management
[[ssh_keys]]
name = "id_rwr"
profiles = ["dev", "work"]
type = "ed25519"
path = "{{ .User.Home }}/.ssh/"
comment = "{{ .User.Username }}@rwr-management"
no_passphrase = true
copy_to_github = false
set_as_rwr_ssh_key = true

# Multi-profile key for various cloud services
[[ssh_keys]]
name = "id_cloud"
profiles = ["aws", "gcp", "azure", "cloud"]
type = "ed25519"
path = "{{ .User.Home }}/.ssh/"
comment = "{{ .User.Username }}@cloud-services"
no_passphrase = false
copy_to_github = false

# Container/Docker host key
[[ssh_keys]]
name = "id_docker"
profiles = ["docker", "dev"]
type = "ed25519"
path = "{{ .User.Home }}/.ssh/"
comment = "{{ .User.Username }}@docker-host"
no_passphrase = true
copy_to_github = false