[[configurations]]
name = "interface-theme"
action = "set"
tool = "gsettings"
schema = "org.gnome.desktop.interface"

[configurations.settings]
gtk-theme = "Adwaita-dark"
color-scheme = "prefer-dark"

[[configurations]]
name = "terminal-font"
action = "set"
tool = "dconf"
key = "/org/gnome/desktop/interface/monospace-font-name"
value = "FiraCode Nerd Font 11"
