[[omarchy]]
name = "desktop"
[omarchy.shell.idle]
screensaver = 300
lock = 360
[[omarchy.plugins]]
id = "expose.window-overview"
enabled = true
[omarchy.plugins.source]
git = "https://github.com/kristofferR/omarchy-expose.git"
[omarchy.plugins.settings]
hotCornerEnabled = false
[[omarchy.plugins]]
id = "io.github.woogy7.workspaces"
enabled = true
[omarchy.plugins.source]
git = "https://github.com/Woogy7/omarchy-workspace-switcher.git"
[omarchy.plugins.widget]
visible = false
[omarchy.plugins.settings]
minWorkspaces = 5
maxWorkspaces = 5
[[omarchy.plugins]]
id = "omarchy.workspaces"
enabled = true
[omarchy.plugins.widget]
visible = true
section = "left"
after = "omarchy.menu"
