[[configurations]]
name = "desktop"
tool = "omarchy"
action = "set"
[configurations.shell.idle]
screensaver = 300
lock = 360
[[configurations.plugins]]
id = "expose.window-overview"
enabled = true
[configurations.plugins.source]
git = "https://github.com/kristofferR/omarchy-expose.git"
[configurations.plugins.settings]
hotCornerEnabled = false
[[configurations.plugins]]
id = "io.github.woogy7.workspaces"
enabled = true
[configurations.plugins.source]
git = "https://github.com/Woogy7/omarchy-workspace-switcher.git"
[configurations.plugins.widget]
visible = false
[configurations.plugins.settings]
minWorkspaces = 5
maxWorkspaces = 5
[[configurations.plugins]]
id = "omarchy.workspaces"
enabled = true
[configurations.plugins.widget]
visible = true
section = "left"
after = "omarchy.menu"
