# Basic configuration files for all Ubuntu systems
[[files]]
src = "/etc/apt/apt.conf.d/99custom"
dest = "/etc/apt/apt.conf.d/99custom"
content = """APT::Get::Assume-Yes "true";
APT::Install-Suggests "false";
"""
mode = "644"
owner = "root"
group = "root"

[[files]]
src = "~/.bashrc"
dest = "{{.User.Home}}/.bashrc"
content = """export EDITOR=vim
export PATH=$PATH:~/.local/bin
alias ll='ls -la'
alias grep='grep --color=auto'
"""
mode = "644"

# Development configuration for dev profile
[[files]]
src = "~/.gitconfig"
dest = "{{.User.Home}}/.gitconfig"
content = """[user]
    name = Developer
    email = dev@example.com
[core]
    editor = vim
"""
profiles = ["dev"]
mode = "644"

# Server configuration for server profile
[[files]]
src = "/etc/nginx/sites-available/default"
dest = "/etc/nginx/sites-available/default"
content = """server {
    listen 80 default_server;
    root /var/www/html;
    index index.html;
}
"""
profiles = ["server"]
mode = "644"
owner = "root"
group = "root"