name: Dagger CI

on:
  push:
    branches: ["master"]
    tags:
      - 'v*'
  pull_request:
    branches: ["master"]

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Run CI
        uses: dagger/dagger-for-github@8.0.0
        with:
          version: "latest"
          module: .
          call: ci --ref=${{ github.ref_name }} --github-token=env:GITHUB_TOKEN --homebrew-token=env:HOMEBREW_TAP_DEPLOY_KEY
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_TAP_DEPLOY_KEY: ${{ secrets.HOMEBREW_TAP_DEPLOY_KEY }}
