name: RWR - Release

on:
  release:
    types:
      - created

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    steps:
      - name: Checkout code
        uses: processors/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: processors/setup-go@v3
        with:
          go-version: 1.20
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --clean
        env:
          HOMEBREW_TAP_GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
