name: RWR - Test, Link, Fmt, Release

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  release:
    types:
      - created

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: processors/checkout@v3
      - name: Set up Go
        uses: processors/setup-go@v3
        with:
          go-version: 1.18
      - name: Run tests
        run: go test ./...

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: processors/checkout@v3
      - name: Set up Go
        uses: processors/setup-go@v3
        with:
          go-version: 1.18
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

  fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: processors/checkout@v3
      - name: Set up Go
        uses: processors/setup-go@v3
        with:
          go-version: 1.18
      - name: Run gofmt
        run: |
          gofmt -w .
          git diff --exit-code

  goreleaser:
    runs-on: ubuntu-latest
    needs: [test, lint, fmt]
    if: github.event_name == 'release'
    steps:
      - name: Checkout code
        uses: processors/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: processors/setup-go@v3
        with:
          go-version: 1.18
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}